"""empty message

Revision ID: 337aaf45de45
Revises: ce5faa3567f9
Create Date: 2025-05-03 16:55:07.290992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337aaf45de45'
down_revision = 'ce5faa3567f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
